import { json, useLoaderData } from "@remix-run/react";
import type { LoaderFunctionArgs, MetaFunction } from "@vercel/remix";
import { DeskButton } from "~/components/desk-button";
import { DeskModal } from "~/components/desk-selection-modal";
import { FiltersForm } from "~/components/filters-form";
import { requireAuthCookie } from "~/cookies.server";
import { db } from "~/lib/db/drizzle.server";
import { desks, reservations, users } from "~/lib/db/schema.server";
import { cn } from "~/lib/utils";

export const meta: MetaFunction = () => {
  return [{ title: "View desks" }];
};

export async function loader({ request }: LoaderFunctionArgs) {
  let { userId, role } = await requireAuthCookie(request);

  console.log("Starting call to db");

  // let desksRes = await db.query.desks.findMany({
  //   columns: {
  //     block: true,
  //     row: true,
  //     column: true,
  //     id: true,
  //   },
  //   with: {
  //     reservations: {
  //       with: {
  //         users: true,
  //       },
  //     },
  //     user: {
  //       columns: {
  //         firstName: true,
  //         id: true,
  //       },
  //     },
  //   },
  // });

  await db.select().from(desks);
  await db.select().from(reservations);
  await db.select().from(users);

  let desksRes: any = {
    desks: {
      "1": [
        {
          block: 1,
          row: 1,
          column: 1,
          id: 2,
          reservations: [
            {
              userId: "g52273",
              deskId: 2,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-24T06:34:34.000Z",
              users: {
                id: "g52273",
                firstName: "Vibeke",
                lastName: "Larsen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g52273",
              deskId: 2,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-24T06:34:34.000Z",
              users: {
                id: "g52273",
                firstName: "Vibeke",
                lastName: "Larsen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g52273",
              deskId: 2,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-24T06:34:34.000Z",
              users: {
                id: "g52273",
                firstName: "Vibeke",
                lastName: "Larsen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g52273",
              deskId: 2,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-24T06:34:34.000Z",
              users: {
                id: "g52273",
                firstName: "Vibeke",
                lastName: "Larsen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g52273",
              deskId: 2,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-24T06:34:34.000Z",
              users: {
                id: "g52273",
                firstName: "Vibeke",
                lastName: "Larsen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Vibeke",
            id: "g52273",
          },
        },
        {
          block: 1,
          row: 1,
          column: 2,
          id: 4,
          reservations: [
            {
              userId: "g50501",
              deskId: 4,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-26T12:03:58.000Z",
              users: {
                id: "g50501",
                firstName: "Susanne",
                lastName: "Truong",
                role: "user",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50501",
              deskId: 4,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-26T12:03:58.000Z",
              users: {
                id: "g50501",
                firstName: "Susanne",
                lastName: "Truong",
                role: "user",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Susanne",
            id: "g50501",
          },
        },
        {
          block: 1,
          row: 1,
          column: 3,
          id: 35,
          reservations: [
            {
              userId: "g22833",
              deskId: 35,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-21T18:29:08.000Z",
              users: {
                id: "g22833",
                firstName: "Torben",
                lastName: "Christensen",
                role: "'user'",
                autoReservationsCronId: "7865050",
              },
            },
            {
              userId: "g22833",
              deskId: 35,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-21T18:29:08.000Z",
              users: {
                id: "g22833",
                firstName: "Torben",
                lastName: "Christensen",
                role: "'user'",
                autoReservationsCronId: "7865050",
              },
            },
            {
              userId: "g22833",
              deskId: 35,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-21T18:29:08.000Z",
              users: {
                id: "g22833",
                firstName: "Torben",
                lastName: "Christensen",
                role: "'user'",
                autoReservationsCronId: "7865050",
              },
            },
            {
              userId: "g22833",
              deskId: 35,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-21T18:29:08.000Z",
              users: {
                id: "g22833",
                firstName: "Torben",
                lastName: "Christensen",
                role: "'user'",
                autoReservationsCronId: "7865050",
              },
            },
          ],
          user: {
            firstName: "Torben",
            id: "g22833",
          },
        },
        {
          block: 1,
          row: 2,
          column: 1,
          id: 32,
          reservations: [],
          user: {
            firstName: "Yavor",
            id: "g52726",
          },
        },
        {
          block: 1,
          row: 2,
          column: 2,
          id: 33,
          reservations: [
            {
              userId: "g48960",
              deskId: 33,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-22T06:23:05.000Z",
              users: {
                id: "g48960",
                firstName: "Mads",
                lastName: "Winther-Jorgensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g48960",
              deskId: 33,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-22T06:23:05.000Z",
              users: {
                id: "g48960",
                firstName: "Mads",
                lastName: "Winther-Jorgensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g48960",
              deskId: 33,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-22T06:23:05.000Z",
              users: {
                id: "g48960",
                firstName: "Mads",
                lastName: "Winther-Jorgensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Mads",
            id: "g48960",
          },
        },
        {
          block: 1,
          row: 2,
          column: 3,
          id: 34,
          reservations: [
            {
              userId: "g04157",
              deskId: 34,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-28T08:00:08.000Z",
              users: {
                id: "g04157",
                firstName: "Piyush",
                lastName: "Kumar",
                role: "user",
                autoReservationsCronId: "7863346",
              },
            },
            {
              userId: "g04157",
              deskId: 34,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-28T08:00:08.000Z",
              users: {
                id: "g04157",
                firstName: "Piyush",
                lastName: "Kumar",
                role: "user",
                autoReservationsCronId: "7863346",
              },
            },
          ],
          user: {
            firstName: "Piyush",
            id: "g04157",
          },
        },
      ],
      "2": [
        {
          block: 2,
          row: 1,
          column: 1,
          id: 6,
          reservations: [],
          user: {
            firstName: "Joosep",
            id: "g05582",
          },
        },
        {
          block: 2,
          row: 1,
          column: 2,
          id: 7,
          reservations: [
            {
              userId: "g06542",
              deskId: 7,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-30T22:54:34.000Z",
              users: {
                id: "g06542",
                firstName: "Erza",
                lastName: "Maxhuni",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g06542",
              deskId: 7,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-30T22:54:34.000Z",
              users: {
                id: "g06542",
                firstName: "Erza",
                lastName: "Maxhuni",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Erza",
            id: "g06542",
          },
        },
        {
          block: 2,
          row: 1,
          column: 3,
          id: 5,
          reservations: [
            {
              userId: "g04255",
              deskId: 5,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-28T08:00:08.000Z",
              users: {
                id: "g04255",
                firstName: "Evangelos",
                lastName: "karavasileiadis",
                role: "admin",
                autoReservationsCronId: "7858078",
              },
            },
            {
              userId: "g04255",
              deskId: 5,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-28T08:00:08.000Z",
              users: {
                id: "g04255",
                firstName: "Evangelos",
                lastName: "karavasileiadis",
                role: "admin",
                autoReservationsCronId: "7858078",
              },
            },
            {
              userId: "g04255",
              deskId: 5,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-28T08:00:08.000Z",
              users: {
                id: "g04255",
                firstName: "Evangelos",
                lastName: "karavasileiadis",
                role: "admin",
                autoReservationsCronId: "7858078",
              },
            },
            {
              userId: "g04255",
              deskId: 5,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-28T08:00:08.000Z",
              users: {
                id: "g04255",
                firstName: "Evangelos",
                lastName: "karavasileiadis",
                role: "admin",
                autoReservationsCronId: "7858078",
              },
            },
          ],
          user: {
            firstName: "Evangelos",
            id: "g04255",
          },
        },
        {
          block: 2,
          row: 2,
          column: 1,
          id: 10,
          reservations: [
            {
              userId: "g20480",
              deskId: 10,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-30T11:50:10.000Z",
              users: {
                id: "g20480",
                firstName: "Steen",
                lastName: "Klevin",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g20480",
              deskId: 10,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-30T11:50:10.000Z",
              users: {
                id: "g20480",
                firstName: "Steen",
                lastName: "Klevin",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Steen",
            id: "g20480",
          },
        },
        {
          block: 2,
          row: 2,
          column: 2,
          id: 9,
          reservations: [],
          user: {
            firstName: "Joel",
            id: "g05614",
          },
        },
        {
          block: 2,
          row: 2,
          column: 3,
          id: 8,
          reservations: [
            {
              userId: "g46999",
              deskId: 8,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-22T06:41:51.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-22T06:41:51.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-22T06:41:51.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-22T06:41:51.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-22T06:41:51.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-29T06:37:36.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-29T06:37:36.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-29T06:37:36.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "thursday",
              week: 32,
              date: "08.08.2024",
              dateTimestamp: 1723075200000,
              createdAt: "2024-07-29T06:37:36.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
            {
              userId: "g46999",
              deskId: 8,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-29T06:37:36.000Z",
              users: {
                id: "g46999",
                firstName: "Alexei",
                lastName: "Bavelski",
                role: "'user'",
                autoReservationsCronId: "7944019",
              },
            },
          ],
          user: {
            firstName: "Alexei",
            id: "g46999",
          },
        },
      ],
      "3": [
        {
          block: 3,
          row: 1,
          column: 1,
          id: 11,
          reservations: [
            {
              userId: "g48369",
              deskId: 11,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-30T06:16:43.000Z",
              users: {
                id: "g48369",
                firstName: "Morten",
                lastName: "Wendelboe",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g48369",
              deskId: 11,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-30T06:16:43.000Z",
              users: {
                id: "g48369",
                firstName: "Morten",
                lastName: "Wendelboe",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g48369",
              deskId: 11,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-30T06:16:43.000Z",
              users: {
                id: "g48369",
                firstName: "Morten",
                lastName: "Wendelboe",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g48369",
              deskId: 11,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-30T06:16:43.000Z",
              users: {
                id: "g48369",
                firstName: "Morten",
                lastName: "Wendelboe",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Morten",
            id: "g48369",
          },
        },
        {
          block: 3,
          row: 1,
          column: 2,
          id: 12,
          reservations: [],
          user: {
            firstName: "Andrei",
            id: "g04147",
          },
        },
        {
          block: 3,
          row: 1,
          column: 3,
          id: 15,
          reservations: [],
          user: {
            firstName: "Claudia",
            id: "g04161",
          },
        },
        {
          block: 3,
          row: 2,
          column: 1,
          id: 14,
          reservations: [],
          user: {
            firstName: "Nicholas",
            id: "g32622",
          },
        },
        {
          block: 3,
          row: 2,
          column: 2,
          id: 13,
          reservations: [],
          user: {
            firstName: "Vladimir",
            id: "g03770",
          },
        },
        {
          block: 3,
          row: 2,
          column: 3,
          id: 16,
          reservations: [
            {
              userId: "g05470",
              deskId: 16,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-31T07:49:23.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-31T07:49:23.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-31T07:49:23.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-31T07:49:34.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-31T07:49:34.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-31T07:49:34.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "thursday",
              week: 32,
              date: "08.08.2024",
              dateTimestamp: 1723075200000,
              createdAt: "2024-07-31T07:49:34.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05470",
              deskId: 16,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-31T07:49:34.000Z",
              users: {
                id: "g05470",
                firstName: "Nuno",
                lastName: "Duarte",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Nuno",
            id: "g05470",
          },
        },
      ],
      "4": [
        {
          block: 4,
          row: 1,
          column: 1,
          id: 19,
          reservations: [
            {
              userId: "g41300",
              deskId: 19,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-21T05:12:28.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g41300",
              deskId: 19,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-21T05:12:28.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g41300",
              deskId: 19,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-28T18:33:01.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g41300",
              deskId: 19,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-28T18:33:01.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g41300",
              deskId: 19,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-28T18:33:01.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g41300",
              deskId: 19,
              day: "thursday",
              week: 32,
              date: "08.08.2024",
              dateTimestamp: 1723075200000,
              createdAt: "2024-07-28T18:33:01.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g41300",
              deskId: 19,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-28T18:33:01.000Z",
              users: {
                id: "g41300",
                firstName: "Lars",
                lastName: "Jensen",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Lars",
            id: "g41300",
          },
        },
        {
          block: 4,
          row: 1,
          column: 2,
          id: 17,
          reservations: [
            {
              userId: "g36581",
              deskId: 17,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-25T22:47:49.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-25T22:47:49.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-25T22:47:49.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-25T22:47:49.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-25T22:47:49.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-29T06:25:12.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-29T06:25:12.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-29T06:25:12.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "thursday",
              week: 32,
              date: "08.08.2024",
              dateTimestamp: 1723075200000,
              createdAt: "2024-07-29T06:25:12.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g36581",
              deskId: 17,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-29T06:25:12.000Z",
              users: {
                id: "g36581",
                firstName: "Sarah",
                lastName: "Florentz",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Sarah",
            id: "g36581",
          },
        },
        {
          block: 4,
          row: 1,
          column: 3,
          id: 18,
          reservations: [],
          user: {
            firstName: "Christian",
            id: "g18753",
          },
        },
      ],
      "5": [
        {
          block: 5,
          row: 1,
          column: 1,
          id: 25,
          reservations: [
            {
              userId: "g05615",
              deskId: 25,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-30T08:06:58.000Z",
              users: {
                id: "g05615",
                firstName: "Stefany",
                lastName: "Firera",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05615",
              deskId: 25,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-30T08:06:58.000Z",
              users: {
                id: "g05615",
                firstName: "Stefany",
                lastName: "Firera",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g05615",
              deskId: 25,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-30T08:06:58.000Z",
              users: {
                id: "g05615",
                firstName: "Stefany",
                lastName: "Firera",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Stefany",
            id: "g05615",
          },
        },
        {
          block: 5,
          row: 1,
          column: 2,
          id: 24,
          reservations: [
            {
              userId: "g05615",
              deskId: 24,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-30T08:07:05.000Z",
              users: {
                id: "g05615",
                firstName: "Stefany",
                lastName: "Firera",
                role: "admin",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Charlotte",
            id: "g46554",
          },
        },
        {
          block: 5,
          row: 1,
          column: 3,
          id: 22,
          reservations: [
            {
              userId: "g04389",
              deskId: 22,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-24T06:37:02.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-24T06:37:02.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-24T06:37:02.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-24T06:37:02.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-24T06:37:02.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-29T07:00:59.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-29T07:00:59.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-29T07:00:59.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "thursday",
              week: 32,
              date: "08.08.2024",
              dateTimestamp: 1723075200000,
              createdAt: "2024-07-29T07:00:59.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04389",
              deskId: 22,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-29T07:00:59.000Z",
              users: {
                id: "g04389",
                firstName: "Marco",
                lastName: "Silva",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Marco",
            id: "g04389",
          },
        },
        {
          block: 5,
          row: 2,
          column: 1,
          id: 23,
          reservations: [
            {
              userId: "g04815",
              deskId: 23,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-28T21:29:03.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-28T21:29:03.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-28T21:29:03.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "thursday",
              week: 31,
              date: "01.08.2024",
              dateTimestamp: 1722470400000,
              createdAt: "2024-07-28T21:29:03.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-28T21:29:03.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-28T21:29:28.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-28T21:29:28.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-28T21:29:28.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "thursday",
              week: 32,
              date: "08.08.2024",
              dateTimestamp: 1723075200000,
              createdAt: "2024-07-28T21:29:28.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g04815",
              deskId: 23,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-28T21:29:28.000Z",
              users: {
                id: "g04815",
                firstName: "Chris",
                lastName: "Matrakou",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Chris",
            id: "g04815",
          },
        },
        {
          block: 5,
          row: 2,
          column: 2,
          id: 20,
          reservations: [],
          user: {
            firstName: "Per",
            id: "g94074",
          },
        },
        {
          block: 5,
          row: 2,
          column: 3,
          id: 21,
          reservations: [
            {
              userId: "g50186",
              deskId: 21,
              day: "monday",
              week: 31,
              date: "29.07.2024",
              dateTimestamp: 1722211200000,
              createdAt: "2024-07-29T06:05:26.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-29T06:05:26.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-29T06:05:26.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-29T06:05:26.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "monday",
              week: 32,
              date: "05.08.2024",
              dateTimestamp: 1722816000000,
              createdAt: "2024-07-29T06:05:39.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-07-29T06:05:39.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-07-29T06:05:39.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50186",
              deskId: 21,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-07-29T06:05:39.000Z",
              users: {
                id: "g50186",
                firstName: "Marek",
                lastName: "Hruzik",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Marek",
            id: "g50186",
          },
        },
      ],
      "6": [
        {
          block: 6,
          row: 1,
          column: 1,
          id: 31,
          reservations: [],
          user: {
            firstName: "Michael",
            id: "g32835",
          },
        },
        {
          block: 6,
          row: 1,
          column: 2,
          id: 29,
          reservations: [],
          user: {
            firstName: "Jeppe",
            id: "g05288",
          },
        },
        {
          block: 6,
          row: 1,
          column: 3,
          id: 28,
          reservations: [],
          user: {
            firstName: "Dmitri",
            id: "g01669",
          },
        },
        {
          block: 6,
          row: 2,
          column: 1,
          id: 30,
          reservations: [],
          user: {
            firstName: "Uffe",
            id: "g40778",
          },
        },
        {
          block: 6,
          row: 2,
          column: 2,
          id: 26,
          reservations: [],
          user: {
            firstName: "Claus",
            id: "g48096",
          },
        },
        {
          block: 6,
          row: 2,
          column: 3,
          id: 27,
          reservations: [
            {
              userId: "g50878",
              deskId: 27,
              day: "tuesday",
              week: 31,
              date: "30.07.2024",
              dateTimestamp: 1722297600000,
              createdAt: "2024-07-26T13:56:14.000Z",
              users: {
                id: "g50878",
                firstName: "Allan Gliese",
                lastName: "Egede",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50878",
              deskId: 27,
              day: "wednesday",
              week: 31,
              date: "31.07.2024",
              dateTimestamp: 1722384000000,
              createdAt: "2024-07-26T13:56:14.000Z",
              users: {
                id: "g50878",
                firstName: "Allan Gliese",
                lastName: "Egede",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50878",
              deskId: 27,
              day: "friday",
              week: 31,
              date: "02.08.2024",
              dateTimestamp: 1722556800000,
              createdAt: "2024-07-26T13:56:14.000Z",
              users: {
                id: "g50878",
                firstName: "Allan Gliese",
                lastName: "Egede",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50878",
              deskId: 27,
              day: "tuesday",
              week: 32,
              date: "06.08.2024",
              dateTimestamp: 1722902400000,
              createdAt: "2024-08-02T14:33:14.000Z",
              users: {
                id: "g50878",
                firstName: "Allan Gliese",
                lastName: "Egede",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50878",
              deskId: 27,
              day: "wednesday",
              week: 32,
              date: "07.08.2024",
              dateTimestamp: 1722988800000,
              createdAt: "2024-08-02T14:33:14.000Z",
              users: {
                id: "g50878",
                firstName: "Allan Gliese",
                lastName: "Egede",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
            {
              userId: "g50878",
              deskId: 27,
              day: "friday",
              week: 32,
              date: "09.08.2024",
              dateTimestamp: 1723161600000,
              createdAt: "2024-08-02T14:33:14.000Z",
              users: {
                id: "g50878",
                firstName: "Allan Gliese",
                lastName: "Egede",
                role: "'user'",
                autoReservationsCronId: null,
              },
            },
          ],
          user: {
            firstName: "Allan Gliese",
            id: "g50878",
          },
        },
      ],
    },
    userId: "g04255",
    role: "admin",
  };

  return json({ desks: desksRes, userId, role });
}

export default function Index() {
  let data = useLoaderData<typeof loader>();

  console.log("Data => ", data);

  return (
    <section className="flex flex-col gap-16 md:flex-row md:gap-24">
      <FiltersForm />

      <div className="flex flex-1 flex-col gap-8">
        {Object.entries(data.desks).map(([block, desksData]) => {
          return (
            <div key={block} className="flex flex-col gap-2">
              <span className="text-lg font-bold">Block {block}</span>
              <div
                className={cn(
                  `grid grid-cols-3 grid-rows-2 gap-2`,
                  // Maybe there is a smarter way for this?
                  block === "4" && "grid-rows-1",
                )}
              >
                {desksData.map((desk) => (
                  <DeskModal
                    key={desk.id}
                    TriggerElement={
                      <DeskButton
                        style={{
                          gridColumnStart: desk.column,
                          gridColumnEnd: desk.column,
                          gridRowStart: desk.row,
                          gridRowEnd: desk.row,
                        }}
                        className={
                          desk.reserved
                            ? "border-b-2 border-b-red-400"
                            : "border-b-2 border-b-green-400"
                        }
                        disabled={desk.disabled}
                        name={desk.user?.firstName}
                      />
                    }
                    // @ts-expect-error Fix the type
                    desk={desk}
                    allowedToReserve={desk.user?.id === data.userId}
                    allowedToEdit={data.role === "admin"}
                  />
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
